send_command:
  description: Sends a command to the server.
  fields:
    bridge:
      name: Bridge
      description: Server to send the command to.
      example: ""
      required: true
      selector:
        device:
          integration: system_bridge
    command:
      name: Command
      description: Command to send to the server.
      required: true
      example: "echo"
      selector:
        text:
    arguments:
      name: Arguments
      description: Arguments to send to the server.
      required: false
      default: ""
      example: "hello"
      selector:
        text:
